import React from 'react'
import Head from 'next/head'
import Nav from '@/components/layouts/Nav'
import Footer from '@/components/layouts/Footer'

type Props = {
  children: React.ReactNode
}

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Real World App with Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        {children}
        <Footer />
      </main>
    </>
  )
}

export default Layout
